Bu yazıda Numpy'da diziler oluşturmayı ve dizinin veri türünü belirlemeyi göreceğiz.

In [1]:
import numpy as np

## Numpy Dizisi Oluşturma

Python'daki liste, dizi, tuple gibi iterable (tekrarlanabilir) veri türlerinden `np.array()` fonksiyonu ile Numpy dizisi oluşturabilirsiniz.

In [2]:
np.array([1 ,2 ,3 ,4 ,5])

array([1, 2, 3, 4, 5])

Dizinin tüm elemanları integer olduğundan dizinin türü integer oldu. Eğer farklı türde veri girerseniz, mümkünse Numpy tüm değerleri aynı veri tipine çevirerek kaydeder. Mesela integer'lerin bulunduğu bir dizide float da varsa tüm veriler float olarak kaydedilir.

In [3]:
np.array([1 ,2 ,3 ,4 ,5, 1.5])

array([1. , 2. , 3. , 4. , 5. , 1.5])

Oluşturacağınız dizinin veri tipini **dtype** parametresiyle belirleyebilirsiniz.

In [4]:
np.array([1,2,3], dtype=float)

array([1., 2., 3.])

Numpy dizilerinin Python listesinden bir diğer farkı da çok boyutlu dizi oluşturulabilmesidir. Liste içi listeler, iki boyutlu dizilerdeki satırlar olarak çevrilir.

In [5]:
np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Sıfırdan Numpy Dizisi Oluşturma
Numpy'da sıfırdan yeni diziler üretmek için çeşitli fonksiyonlar var. Bunlara parametre olarak uzunluk vererek fonksiyonun belirttiği diziyi oluşturabilirsiniz. `dtype` parametresiyle de oluşturulacak dizinin türü belirlenir.

In [6]:
np.zeros(5) # sıfırlardan oluşan dizi

array([0., 0., 0., 0., 0.])

In [7]:
np.ones(3, dtype=int) # birlerden oluşan dizi

array([1, 1, 1])

In [8]:
np.full(5, 3.14) # elemanları 3,14 olan 5 elemanlı dizi

array([3.14, 3.14, 3.14, 3.14, 3.14])

In [9]:
np.linspace(0, 1, 10) # 0 ile 1 aralığını 10'a bölüp parçaları dizi yapar

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

**np.arange**, range fonksiyonu ile aynı şekilde kullanılır

In [10]:
np.arange(0, 100, 5) # 0'dan 100'e beşer beşer sayıların bulunduğu dizi

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [11]:
np.random.random(5) # 5 uzunluğunda 0-1 aralığında rastgele sayı üretir

array([0.60268534, 0.57004332, 0.48193943, 0.63537436, 0.4282472 ])

In [12]:
np.random.randint(0, 10, 15) # 15 uzunluğunda 0 ile 10 arasında integer'larla dolu dizi

array([1, 2, 1, 7, 3, 5, 8, 9, 6, 4, 2, 4, 6, 2, 9])

**np.empty**, np.zeros gibi dizi üretir. Ama farklı olarak diziyi sıfırlarla doldurmaz. Yer kaplayacağı Ram'de ne veri varsa onunla doldurur. Bunun sonucu olarak da np.zeros ve türevlerinden çok daha hızlıdır.

In [13]:
np.empty(11)

array([4.68194120e-310, 4.68194109e-310, 6.90120588e-310, 6.90122171e-310,
       6.90122356e-310, 6.90122123e-310, 6.90122359e-310, 6.90122358e-310,
       6.90122356e-310, 6.90122354e-310, 4.74303020e-322])

Dizi uzunluğunu belirttiğiniz parametreye tuple, liste gibi elemanlar vererek çok boyutlu diziler oluşturabilirsiniz. İki boyutlu diziler için (satır sayısı, sütun sayısı) olarak belirtebilirsiniz.

In [14]:
np.zeros((2,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

## Numpy Standart Veri Türleri
Numpy dizilerindeki tüm elemanların veri tipi aynıdır. Bu veri tipi dtype parametresi ile belirtilir. Veri tipi yazı (string) veya Numpy objesi olabilir.

In [15]:
np.empty(5, dtype="int16") # np.empty(5, dtype=np.int16) ile aynı

array([256, 257, 257, 257, 257], dtype=int16)

Sık kullanılan veri türleri:
- bool_
- int_
- int8
- int16
- uint64
- float_
- float32
- complex_
- complex64

Daha fazlasını [Numpy dokümentasyonunda veri türleri](https://numpy.org/devdocs/user/basics.types.html) sayfasından bulabilirsiniz.