Veri biliminde verilerin temeli Numpy dizilerine dayanır. İleride göreceğimiz Pandas gibi diğer veri araçları da Numpy dizilerini kullanır. Bu bölümde Numpy dizileri ile ilgili işlemlere değineceğiz.

## Dizi Özellikleri

[Önceden](#) öğrendiğimiz gibi iki boyutlu diziyi aşağıdaki gibi tanımlayabiliriz:

In [1]:
import numpy as np

In [2]:
dizi2d = np.random.randint(50, size=(3,4)) # 0-50 arası rakamlarla 3x4'lük rastgele dizi oluştur,
dizi2d

array([[35, 13,  7,  0],
       [31, 12, 30, 17],
       [17, 43,  6, 40]])

Dizilerin, kendileri hakkında bilgi sahibi olabileceğiniz bazı öznitelikleri (attributes) vardır:

In [3]:
print("Dizinin boyutu:", dizi2d.ndim)
print("Dizinin şekli (eksenlerinin uzunlukları):", dizi2d.shape)
print("Dizinin eleman sayısı:", dizi2d.size)
print("Dizinin elemanlarının veri türü:", dizi2d.dtype)
print("Dizinin bir elemanının bayt cinsinden boyutu:", dizi2d.itemsize)
print("Dizinin bayt cinsinden boyutu:", dizi2d.nbytes)

Dizinin boyutu: 2
Dizinin şekli (eksenlerinin uzunlukları): (3, 4)
Dizinin eleman sayısı: 12
Dizinin elemanlarının veri türü: int64
Dizinin bir elemanının bayt cinsinden boyutu: 8
Dizinin bayt cinsinden boyutu: 96


## Bir Elemana Ulaşmak

Numpy dizilerinde veriye ulaşmak için Python'daki liste verilerine ulaşma yöntemlerinin aynısı kullanılır.

In [4]:
dizi = np.random.randint(10, size=5)
print("Dizi:", dizi)
print(dizi[2], dizi[-1])

Dizi: [2 6 2 5 8]
2 8


Çok boyutlu dizilerde indisler arasına virgül konarak diğer eksenlerdeki indisler belirtilir. Örneğin iki boyutlu bir dizi için `[2,3]` ifadesi, ikinci satırın üçüncü sütunu anlamına gelir.

In [5]:
print("Dizi:\n", dizi2d, "\nEleman:", dizi2d[2,1])

Dizi:
 [[35 13  7  0]
 [31 12 30 17]
 [17 43  6 40]] 
Eleman: 43


Python listelerindeki gibi `[3:5]` şeklinde 3 ile 5 aralığındakileri alabilirsiniz. Çok boyutlu diziler için aralara virgüller koyarak işlemlerinizi yine yapabilirsiniz (ör: `dizi[:1, 1:4:2]`).

> Hatırla: Dilimleme (slicing) işlemi şu şekilde kullanılır: `[bas:son:atlama]`

In [6]:
dizi2d[2, ::-1] # dizinin ikinci satırını tersten yaz

array([40,  6, 43, 17])

Numpy dizilerinin tek tip verilerden oluşmasından dolayı diziye farklı tipte veri kaydetmeye çalıştırsanız, Numpy onu dizinin tipine çevirerek kaydeder.

In [7]:
print(dizi.dtype)
print(dizi[0])
dizi[0] = 6.7
print(dizi[0])

int64
2
6


> Burada size önerim, şimdi iki veya üç boyutlu rastgele bir dizi oluşturun ve belirlerdiğiniz elemanlara erişmeye çalışın.

## Dizileri Yeniden Şekillendirme

Dizileri yeniden şekillendirmenin en iyi yolu `reshape()` fonksiyonunu kullanmaktır. Mesela 9 elemanlı diziyi 3x3'lük diziye aşağıdaki gibi çevirebiliriz:

In [8]:
onakadar = np.arange(1,10)
onakadar

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
onakadar.reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Dizinin elemanlarını bir alt boyuta koymak için aşağıdaki yöntemi kullanabilirsiniz.

In [10]:
onakadar[np.newaxis]

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

## Dizi Birleştirme ve Bölme

### Dizi Birleştirme

Dizileri birleştirmek için **concatenate**, **hstack** ve **vstack** fonksiyonları kullanılır. Bu fonksiyonlarla iki veya daha fazla diziyi birleştirebilirsiniz.

Concatenate fonksiyonu parametre olarak birleştirilecek dizileri liste veya tuple olarak alır.

In [11]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6])

Concatenate fonksiyonu ayrıca çok boyutlu dizileri de birleştirebilir.

In [12]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.array([[10, 20, 30],
              [40, 50, 60]])
np.concatenate((a, b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 20, 30],
       [40, 50, 60]])

**axis** parametresi ile hangi boyuttan birleştireceğinizi de belirtebilirsiniz. 0 (öntanımlı olan) dikey, 1 yatay olarak birleştirir.

In [13]:
np.concatenate((a, b), axis=1)

array([[ 1,  2,  3, 10, 20, 30],
       [ 4,  5,  6, 40, 50, 60]])

Ama çok boyutlu dizileri birleştirmek için axis parametresiyle concatenate kullanmak yerine `vstack` (vertical = dikey) ve `hstack` (horizontal = yatay) kullanmak kodun okunabilirliğini arttırır ve tercih edilir.

In [14]:
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 20, 30],
       [40, 50, 60]])

In [15]:
np.hstack((a,b))

array([[ 1,  2,  3, 10, 20, 30],
       [ 4,  5,  6, 40, 50, 60]])

### Dizi Bölme

Diziyi birden fazla parçaya ayırmak için `split()` fonksiyonundan yararlanılır. Birinci parametreye dizi, ikinci parametreye de dizinin bölünecek yerleri yazılır.

In [16]:
dizi = np.arange(10)
dizi

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.split(dizi, [3]) # diziyi üçüncü elemanından böler. İkiye ayırıp liste olarak döndürür

[array([0, 1, 2]), array([3, 4, 5, 6, 7, 8, 9])]

In [18]:
np.split(dizi, [3, 6]) # diziyi üçüncü ve altıncı elemanından böler

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8, 9])]

Çok boyutlu dizileri `vsplit` ve `hsplit` ile bölebilirsiniz. Ayrıca `dsplit` fonksiyonu da üçüncü boyutta keser.

In [19]:
ikiBoyutlu = np.array(np.split(dizi[1:9], [4]))
ikiBoyutlu

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [20]:
np.hsplit(ikiBoyutlu, [2])

[array([[1, 2],
        [5, 6]]),
 array([[3, 4],
        [7, 8]])]