Bir dizi ile bir veriyi aritmetik bir işleme soktuğumuzda iki veri de aynı büyüklükte olmasa da işlem yapılabilir.

In [1]:
import numpy as np

In [2]:
dizi = np.arange(4)
print(dizi)
print(dizi + 5)

[0 1 2 3]
[5 6 7 8]


Örnekte toplananlardan biri tek boyutlu diziyken diğeri bir sayı. Ve toplama işlemi yapılırken sayı, dizi ile aynı uzunlukta o sayılardan oluşan diziymiş gibi davrandı. Bunu çok boyutlu dizilerde de yapabiliriz:

In [3]:
dizi1 = np.array([1, 2, 3])
dizi2 = np.arange(1,10).reshape(3, 3)

print("Dizi1:", dizi1)
print("Dizi2", dizi2)
print("Toplam:\n", dizi1 + dizi2)

Dizi1: [1 2 3]
Dizi2 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Toplam:
 [[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


Yukarıdaki örneği de incelerseniz; `dizi1`in sütun sayısı `dizi2` ile aynıydı ve satırını tekrar ederek `dizi2` ile aynı satır sayısına sahip gibi davrandı. İki boyutlu bir dizi gibi davrandı ve toplama işlemi yapıldı.

Matematikteki ortak çarpan parantezine alma özelliğine de benzetebileceğimiz bu kurallara Broadcasting denir. Broadcasting kuralları şöyledir:

1. Boyut sayıları farklı olan iki dizide; boyut sayısı az olan dizi, diğer dizi ile eşit uzunlukta olan ekseninden çoğaltılır.
2. Eğer hiçbir boyutunun uzunluğu tutmuyorsa eksenlerinden biri 1 olan dizi diğerine uygun olacak şekilde çoğaltılır.
3. Boyut uzunlukları ne birbirlerine ne de bire eşit olmayan dizilerle işlem yapılamaz, hata verir.

In [4]:
a = np.ones((2,3,4))
b = np.random.randint(10, size=(3,1))
print("a:", a)
print("b:", b)
print("a + b:", a + b)

a: [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
b: [[7]
 [0]
 [5]]
a + b: [[[8. 8. 8. 8.]
  [1. 1. 1. 1.]
  [6. 6. 6. 6.]]

 [[8. 8. 8. 8.]
  [1. 1. 1. 1.]
  [6. 6. 6. 6.]]]


Yukarıdaki örnekte 3 uzunluğundaki eksenleri örtüştüğünden b dizisi, 3 uzunluğundaki ekseni temel alınarak çoğaltılıyor ve işlem gerçekleştiriliyor. Bu işlemi gerçekleştirirken b dizisini hangi biçime soktuğunu görmek için aşağıdaki kod güzel bir örnek:

In [5]:
x = a + b
x - a # böylece sadece boardcasting uygulanmış b dizimiz kaldı

array([[[7., 7., 7., 7.],
        [0., 0., 0., 0.],
        [5., 5., 5., 5.]],

       [[7., 7., 7., 7.],
        [0., 0., 0., 0.],
        [5., 5., 5., 5.]]])