## Dizilerde Karşılaştırma

Pythondaki karşılaştırma operatörlerini dizilerde de kullanabilirsiniz. Bu durumda karşılaştırma dizinin her elemanına yapılacak, True ve False'lardan oluşan bir dizi dönecektir.

In [1]:
import numpy as np

In [2]:
dizi = np.array([1, 2, 3, 4, 5])
dizi < 3

array([ True,  True, False, False, False])

Ayrıca diziler arasında karşılaştırma da yapabilirsiniz. [Broadcasting kuralları](#) aynen geçerlidir.

In [3]:
(dizi % 3) != dizi # dizinin elemanları üçe bölününce kalanı kendisine eşit olmayanlar

array([False, False,  True,  True,  True])

## Boolean Dizilerle Çalışma

Gördüğümüz gibi `dizi < 6` gibi yazımlar bool dizi veriyordu. Şimdi bu bool dizilerle bazı işlemler yapacağız.

Bir bool dizinin içindeki True sayısını `np.count_nonzero()` fonksiyonu ile bulabilirsiniz.

In [4]:
np.count_nonzero(dizi < 3)

2

`axis` parametresi belirterek istediğimiz eksen üzerinde çalışabiliyoruz:

In [5]:
dizi2d = np.array([[1, 10, 100], [2, 20, 200]])
print("Dizi:", dizi2d)
print("Satırdaki 15'den küçük eleman sayısı:", np.count_nonzero(dizi2d < 15, axis=1))

Dizi: [[  1  10 100]
 [  2  20 200]]
Satırdaki 15'den küçük eleman sayısı: [2 1]


Tüm değerlerin True veya False olup olmadığını kontrol etmek için [Aggregation bölümünde](#) gördüğümüz `np.any` ve `np.all` fonksiyonlarını kullanabilirsiniz. Elbette `axis` parametresi bunda da geçerli.

In [6]:
print("Dizide 4'ten küçük sayı var mı:", np.any(dizi < 4))
print("Dizideki tüm değerler 4'ten küçük mü:", np.all(dizi < 4))

Dizide 4'ten küçük sayı var mı: True
Dizideki tüm değerler 4'ten küçük mü: False


Python'dan bildiğimiz &, | gibi mantıksal operatörleri kullanmak da mümkün.

Performans açısından bir farkı yok ama bu mantık operatörlerinin hepsinin bir Numpy fonksiyonu da var. Kodun okunabilirliği açısından kullanılabilir.

| Operatör | Fonksiyon        |
|----------|------------------|
| =        | np.equal         |
| !=       | np.not_equal     |
| <        | np.less          |
| <=       | np.less_equal    |
| >        | np.greater       |
| >=       | np.greater_equal |
| &        | np.bitwise_and   |
| \|       | np.bitwise_or    |
| ^        | np.bitwise_xor   |
| ~        | np.bitwise_not   |

## Bool Dizilerini Maskeleme İşlemi İçin Kullanma

Bool dizileri, veri içinden seçim yapmak için kullanılabilir:

In [7]:
print("Dizi:", dizi2d)
print("\n")
print("Maske:", dizi2d < 15)
print("\n")
print("Maskelenmiş:", dizi2d[dizi2d < 15])

Dizi: [[  1  10 100]
 [  2  20 200]]


Maske: [[ True  True False]
 [ True False False]]


Maskelenmiş: [ 1 10  2]


Gördüğünüz gibi bool işlemi sonucu True olan elemanlar bir dizi olarak verildi.