Önceki bölümlerde basit göstergeleri kullanarak (`dizi[3]`), bölerek (`dizi[5:]`) ve bool maskeleme (`dizi[dizi < 10]`) ile dizi elemanlarına ulaşmayı öğrendik. Şimdi ise diğer bir eleman seçme yöntemi olan fancy indexleme'ye (fancy indexing) bakacağız.

## Fancy Indexing Giriş

Fancy indexing'in mantığı şudur: Dizinin elemanlarına erişmek için elemanlarının indisleri, dizi olarak verilir. Tüm olay bu!

Bir dizinin üç elemanına erişmek isteseydik aşağıdaki gibi yazardık:

In [1]:
import numpy as np

In [2]:
dizi = np.random.randint(100, size=10)
print("Dizi:", dizi)
print("Elemanlar:", [dizi[1], dizi[5], dizi[8]])

Dizi: [52 39  9 30 54 64  5 64 35 35]
Elemanlar: [39, 64, 35]


Diziye; liste, tuple veya dizi olarak indislerin listesini vermek de aynı sonucu sağlar ve Fancy Indexing diye adlandırılır.

In [3]:
indisler = [1, 5, 8]
dizi[indisler]

array([39, 64, 35])

Dizi, dizinin indisine verdiğimiz dizinin biçiminde dizi oluşturur:

In [4]:
secici = np.array([[0, 1], [8,9]])
print("Dizi:", dizi, "\n")
print("Index dizisi:", secici)
print("Seçilmiş dizi:", dizi[secici])

Dizi: [52 39  9 30 54 64  5 64 35 35] 

Index dizisi: [[0 1]
 [8 9]]
Seçilmiş dizi: [[52 39]
 [35 35]]


Çok boyutlu dizilerde de aynı mantıkla çalışabilirsiniz.

## İndexleme İşlemlerini Birleştirme

Fancy indexleme, gördüğümüz diğer indexleme türleriyle birleştirilebilir.

In [5]:
bd = np.array([ [a * 10 ** i for a in range(1, 5)] for i in range(4)])
print("Dizi:", bd)
print("İkinci satırdan sonrasının 1. ve 2. elemanları:", bd[2:, [1,2]])

Dizi: [[   1    2    3    4]
 [  10   20   30   40]
 [ 100  200  300  400]
 [1000 2000 3000 4000]]
İkinci satırdan sonrasının 1. ve 2. elemanları: [[ 200  300]
 [2000 3000]]


## Fancy İndexleme ile Veri Değiştirme

Fancy indexleme ile yaptığımız seçimlerde değişiklik de yapabiliriz:

In [6]:
print("Önce:", dizi)
dizi[[0, 9]] = 1000 # Dizinin 0 ve 9. elemanını 1000 yaptık
print("Sonra:", dizi)

Önce: [52 39  9 30 54 64  5 64 35 35]
Sonra: [1000   39    9   30   54   64    5   64   35 1000]


Dizinin aynı elemanı üzerinde değişiklik yapabilirsiniz:

In [7]:
dizi[[1,1]] = [10, 20]
dizi[1]

20

dizi'nin 1. elemanı ilk 10, sonra 20 oldu. Ancak tekrarlamalı işlem yaparken dikkatli olmakta fayda var:

In [8]:
a = np.zeros(10)
a[[1, 1, 1]] += 1
a

array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0.])

Sonuç olarak `a[1]`in 3 olmasını bekleyebilirsiniz ama `a[1] += 1`, `a[1] = a[1] + 1` demektir ki; yukarıdaki işlem, 1. elemana 3 kez ilk haline (sıfıra) 1 ekle anlamına gelir. Ve değeri 1 olur.

Tekrarlamalı ekleme yapmak isterseniz [Universal Function](#) olan `at` methodunu kullanabilir veya benzer method olan `reduceat`ı da kullanabilirsiniz:

In [9]:
np.add.at(a, [2,2,2], 1)
a

array([0., 1., 3., 0., 0., 0., 0., 0., 0., 0.])