## Numpy'da Hızlı Sıralama

Python'da built-in sıralama fonksiyonları olsa da (`dizi.sort()` gibi), numpy'ın kendi sıralama algoritmaları daha etkili çalışacaktır. Numpy'da sıralama için `np.sort` fonksiyonu kullanılır.

`np.sort(dizi)` şeklinde dizinin sıralanmış halini alabilir veya `dizi.sort()` şeklinde diziyi sıralanmış hale sokabilirsiniz (tabi bu seçenek için dizinin numpy dizisi olması gerekiyor).

In [1]:
import numpy as np

In [2]:
dizi = np.arange(1,10)
np.random.shuffle(dizi) # dizinin elemanlarını rastgele yer değiştirir
print("Dizi:\t\t", dizi)
print("Sıralanmış:\t", np.sort(dizi))

Dizi:		 [6 7 8 2 9 3 5 1 4]
Sıralanmış:	 [1 2 3 4 5 6 7 8 9]


np.sort öntanımlı olarak hızlı sıralama (quicksort) algoritmasını kullanır. `kind` parametresiyle mergesort ve heapsort algoritmaları da kullanılabilir. (Ör. `kind="heapsort"`)

Benzer bir fonksiyon olan `np.argsort()` da, elemanların sıralanmış halinin indislerini verir. Yani en küçük değeri en başa atmak yerine, en küçük değerin indisini başa atar. Sonra [Fancy Indexing](#) bölümünde gördüğümüz gibi dizinin sıralanmış halini alabilirsiniz.

In [3]:
indisSirasi = np.argsort(dizi)
print("Dizi:\t\t", dizi)
print("İndis Sırası:\t", indisSirasi)
print("Sıralanmış Dizi:", dizi[indisSirasi])

Dizi:		 [6 7 8 2 9 3 5 1 4]
İndis Sırası:	 [7 3 5 8 6 0 1 2 4]
Sıralanmış Dizi: [1 2 3 4 5 6 7 8 9]


### Çok Boyutlu Dizilerde Sıralama

Çok boyutlu dizilerde sıralama yapmak için `axis` parametresini kullanabilirsiniz. 0 sütunları, 1 satırları sıralar.

In [4]:
dizi2d = np.random.randint(100, size=(4,6))
print(dizi2d)
print("\n")
print(np.sort(dizi2d, axis=1)) # satırları sırala

[[29 21 29 86 40  5]
 [28 43 71 48 52  0]
 [35 72 54  0 28 19]
 [36  9 66 59  2  1]]


[[ 5 21 29 29 40 86]
 [ 0 28 43 48 52 71]
 [ 0 19 28 35 54 72]
 [ 1  2  9 36 59 66]]


## Kısmi Sıralama: Partition

`np.partition` fonksiyonu, birinci parametre olarak dizi, ikinci parametre olarak da sayı alır. Bu sayıya _K_ diyelim. Dizinin en küçük _K_. elemanından küçük olan sayıları _K_'nin soluna, büyük olan sayıları da sağına atar (saymaya sıfırdan başlamayı unutmayın).

In [5]:
tersDizi = np.arange(10)[::-1]
print("Dizi:\t\t", tersDizi)
print("Partition:\t", np.partition(tersDizi, 5))

Dizi:		 [9 8 7 6 5 4 3 2 1 0]
Partition:	 [4 0 1 2 3 5 8 6 7 9]


Yukarıdaki örnekte 5. eleman olan 5 sayısının solunda 5'ten küçük sayıların, sağında da 5'ten büyük sayıların olduğunu görebilirsiniz.

Son olarak `np.argsort()` fonksiyonunun mantığına benzer şekilde `np.argpartition` fonksiyonu da bulunmakta.